name: Rollup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

    # 👇 Store the dist folder
    - uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: dist


  deploy:
    needs: [build]
    steps:
      # 👇 Get the dist folder
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
      - run: ls dist
